Support go to declaration for `Mapper#qualifiedByName`
mapstruct/mapstruct-idea pull request #119
Opened 2022-12-26 20:18 UTC by thunderhook

This pull request tackles #107.

What it does:
* Provide code-completion for `@Mapping#qualifiedByName`
* Code-complete "local" named methods (from the current mapper class)
* Code-complete "external" named methods (defined by `@Mapper(uses = AnotherMapper.class)`)
* Filters out named methods that are used for `@BeforeMapping/@AfterMapping`: I just provide named methods containing a return type different than `PsiType.VOID` - maybe this needs to be more precise?

What it does not:
* Provide code-completion of the `@BeanMapping#qualifiedByName`: I tried to implement it, but discarded it due to the complexity of nested qualifiers as seen [here](https://stackoverflow.com/a/68966277/1213544)

2023-01-12 20:29 UTC, almogtavor commented
@thunderhook Looks awesome thanks!

2023-01-13 19:05 UTC, thunderhook commented
Since I am not a part of the plugin maintainers, I can't really tell. It depends on the free time of the plugin maintainers (e.g. @filiphr) and if the pull request looks good to them.

If they get time, it usually will be released quickly. 🙂

2023-03-17 10:56 UTC, filiphr requested changes
This is really great work @thunderhook. The functionality is great. I've added some comments to clean it up a bit.

Please let us know if you don't have the time to finish it.

Btw. sorry for the late reply, but I've been pretty busy lately and haven't had enough time to look into this.

2023-03-17 10:56 UTC, filiphr commented on src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java
> +    public static List<PsiClass> resolveUsesConfigClasses(PsiAnnotation mapperAnnotation) {
Can we also look into the `Mapper#config` class for this? We do something with it in `TargetUtils#isBuilderEnabled` (as a reference example). Would also be good to add a test case for it as well

2023-03-17 10:56 UTC, filiphr commented on src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructMappingQualifiedByNameReference.java
> +            .filter( this::methodHasReturnType )
Let's move these checks in the `findAllMethodsFromThisAndReferencedMappers`.  That one is already partially doing this for the named methods in used mappers.

2023-03-17 10:56 UTC, filiphr commented on src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructMappingQualifiedByNameReference.java
> +            .filter( this::methodHasReturnType )
Let's move these checks in the `findAllMethodsFromThisAndReferencedMappers`.  That one is already partially doing this for the named methods in used mappers.

2023-03-17 10:56 UTC, filiphr commented on src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructMappingQualifiedByNameReference.java
> +    private List<PsiMethod> findAllMethodsFromThisAndReferencedMappers(@NotNull PsiMethod mappingMethod) {
I think that it is better if we return a `Stream<PsiMethod>` here

2023-03-17 10:56 UTC, filiphr commented on src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructMappingQualifiedByNameReference.java
> +            String.format(
I think that for this it would be good to show the method parameters here as well. e.g. `StringMapper#trim(String)`.

2023-03-18 13:12 UTC, thunderhook commented
I added the named method resolving of mappers that are referenced by `@MapperConfig`.
I also changed a named method in a test to cover the display of multiple parameters.
Please take a look and let me know if there is something else missing. 🙂

If you have any other ideas for this plugin (with that kind of complexity), please let me know, and I'm willing to help out again. 👍

2023-04-02 13:25 UTC, filiphr commented
That's a lot for your changes @thunderhook. I pushed one more commit with some small polishing.

>If you have any other ideas for this plugin (with that kind of complexity), please let me know, and I'm willing to help out again.

Thanks for offering your help. I think that you can have a look at the open issues to see what is being requested. If you are interested in something let us know. Also if you have some other ideas that you'd like to see let us know, we are more than happy to accept your contributions.

2023-04-02 13:41 UTC, merged