#69 Implement with UAST
mapstruct/mapstruct-idea pull request #70
Opened 2021-03-26 03:17 UTC by ifrankwang

2021-03-27 09:04 UTC, filiphr requested changes
Thanks a lot for the PR @ifrankwang. You saved me quite some time 😄 .

Can you please let me know why we need to change the language for the reference contributors in the plugin xmls?

2021-03-27 09:04 UTC, filiphr commented on build.gradle
> +    version System.getenv().getOrDefault('IDEA_VERSION', '2020.3.3')
Please don't change the `ideaVersion` here. Instead change the version in the `gradle.properties` file

2021-03-28 08:49 UTC, ifrankwang commented on build.gradle
> +    version System.getenv().getOrDefault('IDEA_VERSION', '2020.3.3')
Sure, I'll change it back.

2021-03-28 08:57 UTC, ifrankwang commented
> Thanks a lot for the PR @ifrankwang. You saved me quite some time 😄 .
> 
> Can you please let me know why we need to change the language for the reference contributors in the plugin xmls?

@filiphr Because UAST would noly work in this way. Here's description in the offical document:
> To register extensions applicable to UAST, specify language="UAST" in plugin.xml.

2021-03-28 09:11 UTC, filiphr commented
>Because UAST would noly work in this way. Here's description in the offical document:
>
>>To register extensions applicable to UAST, specify language="UAST" in plugin.xml.

I read that as well, but that would mean that those extensions are applied for all UAST languages. Which means that the `MapstructReferenceContributor` will be applied both for Java and Kotlin. However, I don't think that this is correct, since the `MapstructReferenceContributor` is Java specific (the element patterns are Java specific).

I tried your PR yesterday without using language `UAST` and everything works correctly. I'll integrate your PR without that change and will do a release

2021-03-28 09:17 UTC, ifrankwang commented
Sure.

2021-03-28 09:40 UTC, filiphr commented
I've manually merged this in 6942570183354afabbb109ec874ead116606d27f and also made it work for earlier (pre 2020.3) IntelliJ versions with a1ec88a8771206b337bfa35430cc0735d132e8ab.

Again thanks a lot for the help @ifrankwang

2021-03-28 09:40 UTC, closed without merging